image:
  repository: ghcr.io/mrsddq/ml-platform-infrastructure-on-kubernetes/model-api
  tag: "1.0.0"
  pullPolicy: IfNotPresent

model:
  name: rental-price-baseline
  version: "1.0.0"

replicaCount: 2

service:
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

serviceMonitor:
  enabled: true
